### ISSUE TITLE
Question regarding exactly how to authenticate toggl 

### ISSUE THREAD

**Issue by BigDumbGuy** [HHErebus/tasker-toggl#58]
So I spent 3 hours trying to authenticate my toggl api token in the "me - API token.tsk.xml" after importing it into Tasker and I have no idea now. Do I paste in my api token after the colon? Like this (3456 is an example of my token) - 

https://%TOGGL_TOKEN:3456@www.toggl.com

Is that correct? 

And once that authentication Tasker task is set up, do I have to run it everytime before running one of the toggl task? 

And do I have to type in my api token into each restask? Since I do see the password box under the "auth". 

I'm just so confused haha. Thanks.

**Comment by EQuineOntology** [comment]
Hey there!

What you want to do is to create a global Toggl variable called `%TOGGL_TOKEN` and assign your API key to it. 

Global variables are created like normal variables, but in ALL_CAPS. This is the setup tasker-toggl is expecting

![image](https://user-images.githubusercontent.com/1936168/34208829-1b2434b4-e590-11e7-81d6-ea6f70e3d6e1.png)

The two available authentication methods are either just `%TOGGL_TOKEN` or both `%TOGGL_PW` and `%TOGGL_EMAIL`.

Bar one `/me` example (which I provided as an example of how to authenticate with email and password), all tasks use the API token as an authentication method, so you only need to set the variable itself (no change in RESTask tasks is needed).

You can find more info about how the Toggl API authenticates here: [Authentication](https://github.com/toggl/toggl_api_docs/blob/master/chapters/authentication.md)

**Comment by esolijon** [comment]
I'm unable to import any of the .XML files into Tasker -- when I long-press Tasks>Import and select your .XML file, Tasker says "Error: bad data format." What am I doing incorrectly?
