### ISSUE TITLE
Should start time entry be POST instead of PUT?

### ISSUE THREAD

**Issue by bgrolleman** [HHErebus/tasker-toggl#62]
So I was trying to get things to work, and after some debugging the fix seems to be to use POST instead of PUT

Looking at the at the API docs that seems to confirm this 
https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md

Now I'm happy to make a pull request, but I might be barking up the wrong tree here so opening a quick issue to double check if I'm not overlooking something obvious. 😅

**Comment by EQuineOntology** [comment]
Hi @bgrolleman!

You're certainly welcome to submit the pull request - I actually just noticed I need to update the default endpoints too since those changed with the release of Toggl Track, I'll get it done soon

Cheers!

**Comment by bgrolleman** [comment]
This one wins, smallest pull request of the month for me.

**Comment by EQuineOntology** [comment]
Many thanks! I'll go over the Toggl docs to see if there's any other discrepancies and updates
